sprint 1/step 1
delioncourts/react-burger pull request #1
Opened 2023-08-29 15:47 UTC by delioncourts

Добрый день!

Вёрстка для первого спринта. 

p.s. пробовала при помощи "useRef" сделать красивый скролл до нужного раздела при переключении по табу, но пока не получилось - буду думать дальше :)

Хорошего дня!

2023-08-29 17:53 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Проект соответствует макету
- Хороший codestyle - код логичный и понятный
- Хорошая работа с propTypes

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Булки в конструкторе не должны скролиться - скролиться должен только контент между ними
- У всех компонентов с пропсами должны быть `propTypes`

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-08-29 17:53 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                <Tab value="bun" active={current === 'bun'} onClick={setCurrent}>
**Можно лучше**
при клике на соответвующий таб должен происходить скролл к нужному разделу в списке ингредиентов

Для этого можно задать каждому заголовку соотвующий id (или использовать refы) и вызывать scrollIntoView
Например:

```
  const setTab = (tab) => {
    setCurrent(tab);
    const element = document.getElementById(tab);
    if (element) element.scrollIntoView({ behavior: "smooth" });
  };

```

где заголовкам разделов заданы соответсвующие атрибуты id
https://developer.mozilla.org/ru/docs/Web/API/Element/scrollIntoView

2023-08-30 04:37 UTC, delioncourts commented on src/components/burger-ingredients/burger-ingredients.jsx
> +                <Tab value="bun" active={current === 'bun'} onClick={setCurrent}>
Спасибо большое!

2023-08-30 04:57 UTC, delioncourts commented
Добрый день!

Спасибо большое за ревью!

- Добавила скролл только для элементов - булочки остались на месте, проверила чтобы контейнер для ингридиентов не "выпадал" за пределы экрана;
- Прописала `PropTypes` также для карточки бургера;
- Поправила скорлл по нужному разделу по клику на таб (спасибо за совет!).

Хорошего дня!

2023-08-30 19:39 UTC, andryxxa93 commented
Промежуточная работа принята, вы можете приступать к финальному этапу сдачи работы. Удачи!

2023-10-17 21:43 UTC, closed without merging