Sprint 1/step 2
delioncourts/react-burger pull request #2
Opened 2023-09-03 22:39 UTC by delioncourts

Добрый день!

Второй этап для первого спринта "Написать весь JSX и сверстать". 

Спасибо и хорошего дня!

2023-09-04 16:40 UTC, andryxxa93 requested changes
Необходимо исправить:
- Проект собирается с ошибками.

![Снимок экрана 2023-09-04 в 13 00 32](https://github.com/delioncourts/react-burger/assets/60173362/bc06b012-2906-45b6-8b02-9f6a3ec3cbe5)

- У некоторых компонентов нет `propTypes`
- Модальное окно всё полупрозрачное, но должно быть полупрозрачное только подложка
- Вы создали запрос на получение ингредиентов с бека, но нигде его не испольузете

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-09-04 16:40 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +        return <div>Загружается... Пожалуйста, подождите.</div>;
**Можно лучше**
Лучше создать отдельный компонент Loader с текстом заглушкой. В будущем случаев когда он будет нужен станет больше

2023-09-04 16:40 UTC, andryxxa93 commented on src/components/burger-ingredients/burger-ingredients.jsx
> +    const buns = ingredients.filter(item => item.type === 'bun');
**Можно лучше**
Сложные операции желательно оборачивать в хук `useMemo` чтобы избежать ненужных выполнений. 
https://ru.reactjs.org/docs/hooks-reference.html#usememo

2023-09-04 16:40 UTC, andryxxa93 commented on src/components/ingredient-details/ingredient-details.jsx
> +const IngredientDetails = ({ ingredient }) => {
**Надо исправить**

для этого компонента так же нужно описать PropTypes

2023-09-05 16:45 UTC, delioncourts commented
Добрый день!

Внесла изменения в проект: 

- Убрала ошибку onClose - теперь попап закрывается по клику по крестику, по Esc и по клику по оверлею;
- Добавила PropTypes для Ingredient Details; 
- Поправила прозрачность - теперь прозрачный только оверлей, а окно попапа нет;
- Ингредиенты теперь подгружаются с бэка; 
- Создала отдельный компонент Loader (пока он просто с текстом без особой красоты); 
- Использовала  useMemo в Burger Constructor, в Burger Ingredients не очень получилось :( 

Спасибо!

2023-09-06 09:34 UTC, andryxxa93 commented
**Необходимо исправить**
- Перестала открываться модалка с деталями ингредиента

2023-09-06 15:37 UTC, delioncourts commented
Добрый вечер!

Теперь модалка с ингридиентами также открывается, но не заполняется. Возможно проблема в элементе, который я передаю :( 

Попробовала в IngredientDetails передавать data и соотвественно менять на data.name, однако тогда приложение падает с ошибкой (undefined). 
Если в BurgerIngredients использовать конструкцию для открытия модалки с ингредиентом вида openModal && activeIngredient (передавая текущий элемент), то тогда модалка не открывается. 
В handleIngredientClick в BurgerIngredients в  console.log data это массив, а item undefined. 
Если в модалке заменить data на item, то также открывается пустая модалка (<IngredientDetails data={activeIngredient} />)

2023-09-07 06:20 UTC, andryxxa93 commented
Здравствуйте! 
Смотрите, во-первых вы ничего не передаете в функцию `handleIngredientClick` чтобы это отображалось в деталях ингредиента.

Нужно сделать так
```jsx
                        <BurgerCard
                            card={item}
                            name={item.name}
                            price={item.price}
                            image={item.image}
                            key={item._id}
                            __v={item.__V}
                            onIngredientClick={() => handleIngredientClick(item)}
                        />
```


Второй момент - вы в `IngredientDetails` пытаетесь сразу деструктуризировать детали ингредиента, это круто, но ведь вы их передаете не напрямую, а через проп `data` . Вам надо сначала деструктуризировать его.


```jsx
const IngredientDetails = ({ data }) => {
    const { image_large, name, calories, proteins, fat, carbohydrates } = data;
```

2023-09-07 11:44 UTC, delioncourts commented
Спасибо большое!

- Поправила - теперь данные карточки отображаются корректно (оказалось что все действительно было просто)); 
- Также поправила ошибки PropTypes; 

Хорошего дня!

2023-09-07 19:12 UTC, andryxxa93 commented
Супер, вы отлично поработали!
Поздравляю! Работа принята.
Желаю удачного продолжения обучения!

2023-10-17 21:44 UTC, merged