sprint 6/step 1
delioncourts/react-burger pull request #7
Opened 2024-01-14 22:55 UTC by delioncourts

Добрый день! 6 спринт с юнит тестами (jest) и cypress. Деплой на vercel: https://react-burger-sable.vercel.app/
Спасибо!

2024-01-15 03:42 UTC, ArslanMustafin requested changes
## Code Review

Здравствуйте!

Отличная работа. 🔥

### **Вы молодец!**

- Все юнит-тесты (40 шт) проходят успешно
- Все Cypress тесты проходят успешно
- В readme есть ссылка на проект.

### **Есть небольшое замечание, которое нужно исправить:**

- Нужно вынести вынести базовый адрес сервера в конфиг cypress.

### **Сделает код лучше:**

- Не стоит добавлять префикс `jest` к файлам для тестов. Достаточно того, что вы добавляете `test` в конце. Также, вы можете создать отдельную папку `__test__` и туда класть тесты);

- Чтобы проверить процент покрытия тестами всех файлов, используйте команду `react-scripts test --coverage --watchAll`

- Стоит обращать внимание на предупреждения в терминале, в котором запущен проект. Это хорошие рекомендации, которых следовало бы придерживаться. В противном случае, лучше отключить линтер у строки (куска кода) eslint-disable. Так же добавить комментарий (TODO), объясняющий причину блокировки линтера в данном месте. Суть в том, что мы стараемся писать более чистый код, а если видим, что порой выскакивают предупреждения того же линтера, то оставляем комментарий, объясняющий причину. В коммерческой разработке, когда есть целая команда разработчиков, работающих над одним проектом, эта рекомендация послужит правилом хорошего тона. Неплохая статься по поводу локального отключения линтера: <https://learn.coderslang.com/ru/0023-eslint-disable-for-specific-lines-files-and-folders>;

### **_Подробно эти и более мелкие замечания, отмечены в коде._**

2024-01-15 03:42 UTC, ArslanMustafin commented on cypress/e2e/constructor.cy.ts
> +const testURL = 'http://localhost:3000'
**Надо исправить:**

лучше вынести базовый адрес сервера в конфиг cypress.

<https://docs.cypress.io/guides/references/best-practices#Setting-a-Global-baseUrl>

2024-01-15 03:42 UTC, ArslanMustafin commented on cypress/e2e/constructor.cy.ts
> +    cy.get('[alt="Соус Spicy-X"]').click();
**Можно лучше:**

здесь и далее.

В данном случае лучше искать элементы, используя `cy.contains` либо через `data-cy`.
https://docs.cypress.io/guides/references/best-practices#How-It-Works

2024-01-15 18:05 UTC, delioncourts commented on cypress/e2e/constructor.cy.ts
> +const testURL = 'http://localhost:3000'
Спасибо большое за совет! Вынесла в конфиг и отдельно классно почитать best practices.

2024-01-15 18:12 UTC, delioncourts commented on cypress/e2e/constructor.cy.ts
> +    cy.get('[alt="Соус Spicy-X"]').click();
Спасибо! Попробовала через contains (cy.contains('[alt="Соус Spicy-X"]')), но если его использовать, то тогда тесты падают с ошибкой. Буду думать)

2024-01-15 18:17 UTC, delioncourts commented
Добрый вечер!

Поправила проект 

- Вынесла localhost:3000 в глобальную переменную для cypress; 
- Удалила jest перед тестовыми файлами и вынесла их в отдельную папку __test__ (+ поправила импорты, чтобы тесты не падали); 
- Поправила tsconfig - во время попытки починить другую ошибку, появилась эта. Теперь проблем в консоли нет, также удалось избавиться от пустого экспорта в cypress. 

Хорошего дня!

2024-01-16 03:37 UTC, ArslanMustafin commented on cypress/e2e/constructor.cy.ts
> +    cy.get('[alt="Соус Spicy-X"]').click();
Тут можно чуточку иначе написать `cy.contains('Соус Spicy-X')`.  `contains` - просто ищет подстроку, и возвращает элемент с ней. https://docs.cypress.io/api/commands/contains

2024-01-16 03:38 UTC, ArslanMustafin approved these changes
## Code Review

Здравствуйте!

Отличная работа.🔥

### **Вы молодец! Работа принята.**

Несколько советов для дальнейшего развития:

- Сверстайте несколько небольших проектов для себя, для закрепления знаний, и чтобы можно добавить их в портфолио.

- Ходите на собеседования: опыт прохождения собеседований не менее важен знаний теории, и Вы поймете, какие знания требуются на рынке, и где Вы проседаете.

- Читайте habr и слушаете подкаксты: они очень хорошо расширяют кругозор и позволяют узнать, что происходит в отрасли.

2024-01-16 07:46 UTC, delioncourts commented on cypress/e2e/constructor.cy.ts
> +    cy.get('[alt="Соус Spicy-X"]').click();
Отлично, поняла, спасибо большое что объяснили :) заменила на contains где было с alt.

2024-01-16 13:10 UTC, merged